### ISSUE TITLE
CentOS kernels support

### ISSUE THREAD

**Issue by jollheef** [jollheef/out-of-tree#8]
There's already image generator: https://github.com/jollheef/out-of-tree/tree/master/tools/qemu-centos-img

But no Dockerfile generator yet: https://github.com/jollheef/out-of-tree/blob/master/kernel.go#L104

**Comment by wmealing** [comment]
I'll probably have a go at this with RHEL kernels and CentOS kernels.

**Comment by wmealing** [comment]
I kinda now have a somewhat more believable kernels.toml file:

[[kernels]]
distro_type = "CentOS"
distro_release = "7"
kernel_release = "3.10.0-957.el7.x86_64"
container_name = "out_of_tree_centos_7"
kernel_path = "/home/wmealing/.out-of-tree/kernels/vmlinuz-3.10.0-957.el7.x86_64"
initrd_path = "/home/wmealing/.out-of-tree/kernels/initramfs-3.10.0-957.el7.x86_64.img"
root_f_s = "/home/wmealing/.out-of-tree/images/out_of_tree_centos_7.img"

The pew command fails, but thats likely because the out_of_tree_centos_7.img file is busted.

$ out-of-tree pew
2018/12/21 01:51:54 
[*]     CentOS-7 {3.10.0-957.1.3.el7.x86_64}:  BUILD FAILURE   INSMOD FAILURE   TEST FAILURE 
2018/12/21 01:51:54 
[*]         CentOS-7 {3.10.0-957.el7.x86_64}:  BUILD FAILURE   INSMOD FAILURE   TEST FAILURE

**Comment by jollheef** [comment]
> root_f_fs img file doesn't exist in the correct location, maybe i need to generate it and place it manually, not sure.. Will look into that after i get the above two sorted..

Yep, you need to move it manually.

> The pew command fails, but thats likely because the out_of_tree_centos_7.img file is busted.

Not only because of it. Probably you'll get a issue with e1000e because of CentOS kernels doesn't compiled with it, and I'm not sure that it's exists in initrd.

**Comment by wmealing** [comment]
Is there any downside to using a driver that is supported ?

**Comment by jollheef** [comment]
> Is there any downside to using a driver that is supported ?

No, If you'll find a network device that supported by CentOS kernels out of box – it'll be even much more better.
